### PR TITLE
fix: remove automergeAll

### PR DESCRIPTION
**Pull request by revolunet**

### CODE REVIEW

**Comment by douglasduteil** [comment]
Why because no tests ?

**Comment by revolunet** [comment]
i think its safer to be aware of major changes and review manually

**Comment by douglasduteil** [comment]
In the tests you don't trust @revolunet ;)

**Comment by revolunet** [comment]
humans > bots

**Comment by douglasduteil** [comment]
> :heart: :robot: gives :hurtrealbad: :watch: to :smile: :beer: :peace_symbol: 

IMO it's better to add more tests to prevent most failing scenario than to spend our time reviewing manually unimpactful prs 
Specially on project like this one where [the bot is autonomous since the beginning of the year with little impact on the stability](https://github.com/SocialGouv/legi-data/commits/master/package.json)

**Comment by douglasduteil** [comment]
[AFK discussion]

**Pull request merged**
